global:
  scrape_interval: 5s # 每5秒拉一次数据 

scrape_configs:
  - job_name: 'quiz-arena-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080'] # 'backend' 是docker-compose里的服务名